### ISSUE TITLE
[Footer] Need actual HH email address in footer

### ISSUE THREAD

**Issue by thewildpendulum** [wiliajc87/humblehearts#134]
The footer currently displays `humblehearts@email.com`. I'm going out on a limb and guessing that's not correct.

**Comment by SStrausman** [comment]
Tim, humblehearts@email.com is the email that is listed on their current website. 

We can check with Kara, but I think that's actually correct.

**Comment by SStrausman** [comment]
Checked with Kara. This is indeed the correct email. Closing out this issue.
