### ISSUE TITLE
[Media] Change youtube links to use correct embeddable URL

### ISSUE THREAD

**Issue by thewildpendulum** [wiliajc87/humblehearts#135]
WRONG METHOND
`<iframe src='http://www.youtube.com/watch?v=VIDEO-IDfeature=youtu.be'></iframe>`

CORRECT METHOD
`<iframe src='http://www.youtube.com/embed/VIDEO-ID'></iframe>`

We'll have to change `watch?v=` to `embed/`.

**Comment by SStrausman** [comment]
Videos already are using embed in the database.

What is the problem as it currently is?

Right now to me it looks like the only issue is that these videos are styled pretty poorly?
