### ISSUE TITLE
[Footer] Nav item Community Resources instead of Get Help

### ISSUE THREAD

**Issue by thewildpendulum** [wiliajc87/humblehearts#136]
In the footer, the navigation item for the Community Resources page says "Community Resources", while the main site nav says "Get Help". These need to be consistent.

**Comment by sublimemarch** [comment]
It all needs to be Community Resources, as I mentioned in an email. The header nav item text was changed in a PR when it shouldn't have been.

**Comment by sublimemarch** [comment]
Jamie and I will correct the header's language when we fix the header in a bit.

**Comment by sublimemarch** [comment]
I need someone else to fix the nav items in the header, as that's part of the React code, sorry.

**Comment by thewildpendulum** [comment]
@Nase00 Can you handle that?

**Comment by sowiecki** [comment]
'npm install grunt-cli -g' then 'grunt dev' while in the root directory. That'll run a server to listen for changes and compile it on the fly. Run 'grunt prod' when done and before pushing.

**Comment by KaraAJC** [comment]
from what I'm testing in the navigation branch, this has been corrected
