### ISSUE TITLE
Getting error on events page in local host.

### ISSUE THREAD

**Issue by SStrausman** [wiliajc87/humblehearts#148]
Getting this issue when attempting to view the events page in localhost. I have the flickr secret key in my project already.

@Nase00 any ideas?

![screen shot 2015-05-11 at 9 36 08 am](https://cloud.githubusercontent.com/assets/9004910/7567255/659dcd6c-f7c1-11e4-8ff5-2b3859592812.png)

**Comment by thewildpendulum** [comment]
I believe this has to do with the flickr key. It should be ok on Heroku. You'll have to get the key from someone locally, though

**Comment by SStrausman** [comment]
Did the key change? I have the key in the right folder and this was working yesterday locally.

**Comment by SStrausman** [comment]
Seems to have gone away. Working fine locally now.
